name: flutter_onboarding_slider
description: A page slider with parallex design that allows (Text) widgets or body to slide at a different speed with background.
version: 1.0.11
homepage: https://github.com/appinioGmbH/flutter_packages
repository: https://github.com/appinioGmbH/flutter_packages/tree/main/packages/flutter_onboarding_slider

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3

# The following section is specific to Flutter.
flutter:
